version: "3.7"

services:

  nginx:
    image: nginx:1.23.2-alpine
    hostname: psiz-nx
    container_name: psiz-nx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    networks:
      psiz:
        aliases:
          - psiz-nginx
    restart: always
    depends_on:
      - web
  
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    image: psiz-web
    hostname: psiz-web
    container_name: psiz-web
    volumes:
       - .:/app
    restart: always
    ports:
      - "8080:8080"
    networks:
      psiz:
        aliases:
          - psiz-web
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: psiz-api
    hostname: psiz-api
    container_name: psiz-api
    volumes:
       - .:/app
    restart: always
    ports:
      - "5000:5000"
    networks:
      psiz:
        aliases:
          - psiz-api

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    image: psiz-db
    container_name: psiz-db
    hostname: psiz-db
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      psiz:
        aliases:
          - psiz-db

volumes:
  postgres:

networks:
    psiz:
    default:
      external:
        name: react-psiz-collect_psiz
