version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: psiz-app
    hostname: psiz-app
    container_name: psiz-app
    volumes:
       - .:/app
    restart: always
    ports:
      - "80:80"
      - "5000:5000"
    networks:
      psiz:
        aliases:
          - psiz-app

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    image: psiz-db
    container_name: psiz-db
    hostname: psiz-db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      psiz:
        aliases:
          - psiz-db

volumes:
  postgres:

networks:
    psiz:

