version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    image: psiz-r-app
    hostname: psiz-r-app
    container_name: psiz-r-app
    volumes:
       - .:/app
    restart: always
    ports:
      - "3000:3000"
    networks:
      psiz:
        aliases:
          - psiz-r-app

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    image: psiz-r-db
    container_name: psiz-r-db
    hostname: psiz-r-db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      psiz:
        aliases:
          - psiz-r-db

volumes:
  postgres:

networks:
    psiz:

